//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lam.Libraries.SOA.Proxies.CRMSystem {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.lamresearch.com/contracts/data")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ActiveStatus {
            get {
                return this.ActiveStatusField;
            }
            set {
                if ((this.ActiveStatusField.Equals(value) != true)) {
                    this.ActiveStatusField = value;
                    this.RaisePropertyChanged("ActiveStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditLimit {
            get {
                return this.CreditLimitField;
            }
            set {
                if ((this.CreditLimitField.Equals(value) != true)) {
                    this.CreditLimitField = value;
                    this.RaisePropertyChanged("CreditLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceError", Namespace="http://schemas.lamresearch.com/contracts/faults")]
    [System.SerializableAttribute()]
    public partial class ServiceError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorId {
            get {
                return this.ErrorIdField;
            }
            set {
                if ((this.ErrorIdField.Equals(value) != true)) {
                    this.ErrorIdField = value;
                    this.RaisePropertyChanged("ErrorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.lamresearch.com/contracts/services", ConfigurationName="CRMSystem.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/GetAllCustomer" +
            "s", ReplyAction="http://schemas.lamresearch.com/contracts/services/ICustomerService/GetAllCustomer" +
            "sResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lam.Libraries.SOA.Proxies.CRMSystem.ServiceError), Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/GetAllCustomer" +
            "sServiceErrorFault", Name="ServiceError", Namespace="http://schemas.lamresearch.com/contracts/faults")]
        Lam.Libraries.SOA.Proxies.CRMSystem.Customer[] GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/GetAllCustomer" +
            "s", ReplyAction="http://schemas.lamresearch.com/contracts/services/ICustomerService/GetAllCustomer" +
            "sResponse")]
        System.Threading.Tasks.Task<Lam.Libraries.SOA.Proxies.CRMSystem.Customer[]> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/FindCustomers", ReplyAction="http://schemas.lamresearch.com/contracts/services/ICustomerService/FindCustomersR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lam.Libraries.SOA.Proxies.CRMSystem.ServiceError), Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/FindCustomersS" +
            "erviceErrorFault", Name="ServiceError", Namespace="http://schemas.lamresearch.com/contracts/faults")]
        Lam.Libraries.SOA.Proxies.CRMSystem.Customer[] FindCustomers(string customerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/FindCustomers", ReplyAction="http://schemas.lamresearch.com/contracts/services/ICustomerService/FindCustomersR" +
            "esponse")]
        System.Threading.Tasks.Task<Lam.Libraries.SOA.Proxies.CRMSystem.Customer[]> FindCustomersAsync(string customerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/GetCustomerDet" +
            "ail", ReplyAction="http://schemas.lamresearch.com/contracts/services/ICustomerService/GetCustomerDet" +
            "ailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lam.Libraries.SOA.Proxies.CRMSystem.ServiceError), Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/GetCustomerDet" +
            "ailServiceErrorFault", Name="ServiceError", Namespace="http://schemas.lamresearch.com/contracts/faults")]
        Lam.Libraries.SOA.Proxies.CRMSystem.Customer GetCustomerDetail(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/GetCustomerDet" +
            "ail", ReplyAction="http://schemas.lamresearch.com/contracts/services/ICustomerService/GetCustomerDet" +
            "ailResponse")]
        System.Threading.Tasks.Task<Lam.Libraries.SOA.Proxies.CRMSystem.Customer> GetCustomerDetailAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/AddCustomerDet" +
            "ail", ReplyAction="http://schemas.lamresearch.com/contracts/services/ICustomerService/AddCustomerDet" +
            "ailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Lam.Libraries.SOA.Proxies.CRMSystem.ServiceError), Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/AddCustomerDet" +
            "ailServiceErrorFault", Name="ServiceError", Namespace="http://schemas.lamresearch.com/contracts/faults")]
        bool AddCustomerDetail(Lam.Libraries.SOA.Proxies.CRMSystem.Customer customerDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.lamresearch.com/contracts/services/ICustomerService/AddCustomerDet" +
            "ail", ReplyAction="http://schemas.lamresearch.com/contracts/services/ICustomerService/AddCustomerDet" +
            "ailResponse")]
        System.Threading.Tasks.Task<bool> AddCustomerDetailAsync(Lam.Libraries.SOA.Proxies.CRMSystem.Customer customerDetail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : Lam.Libraries.SOA.Proxies.CRMSystem.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<Lam.Libraries.SOA.Proxies.CRMSystem.ICustomerService>, Lam.Libraries.SOA.Proxies.CRMSystem.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Lam.Libraries.SOA.Proxies.CRMSystem.Customer[] GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<Lam.Libraries.SOA.Proxies.CRMSystem.Customer[]> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public Lam.Libraries.SOA.Proxies.CRMSystem.Customer[] FindCustomers(string customerName) {
            return base.Channel.FindCustomers(customerName);
        }
        
        public System.Threading.Tasks.Task<Lam.Libraries.SOA.Proxies.CRMSystem.Customer[]> FindCustomersAsync(string customerName) {
            return base.Channel.FindCustomersAsync(customerName);
        }
        
        public Lam.Libraries.SOA.Proxies.CRMSystem.Customer GetCustomerDetail(int customerId) {
            return base.Channel.GetCustomerDetail(customerId);
        }
        
        public System.Threading.Tasks.Task<Lam.Libraries.SOA.Proxies.CRMSystem.Customer> GetCustomerDetailAsync(int customerId) {
            return base.Channel.GetCustomerDetailAsync(customerId);
        }
        
        public bool AddCustomerDetail(Lam.Libraries.SOA.Proxies.CRMSystem.Customer customerDetail) {
            return base.Channel.AddCustomerDetail(customerDetail);
        }
        
        public System.Threading.Tasks.Task<bool> AddCustomerDetailAsync(Lam.Libraries.SOA.Proxies.CRMSystem.Customer customerDetail) {
            return base.Channel.AddCustomerDetailAsync(customerDetail);
        }
    }
}
